### ISSUE TITLE
yarn 2 support

### ISSUE THREAD

**Issue by roperzh** [diez/diez#72]
Add support for `yarn 2`, there are a couple of areas in which friction can be anticipated:

- `yarn create diez` & `yarn demo`
- Hot reloading in example projects (due to webpack aliases)
- Autodiscovery of diez plugins
- ...

**Comment by jayarnielsen** [comment]
I am currently running Diez in a Yarn 2 project, but it took some effort to get working. I had to add the following to my .yarnrc.yml file:

```yaml
packageExtensions:
  "diez@*":
    peerDependencies:
      typescript: "*"
  "@diez/cli-core@*":
    dependencies:
      "@types/node": "*"
      "core-js": "*"
    optionalDependencies:
      "@diez/compiler-core": "*"
      "@diez/start": "*"
      "@diez/stdlib": "*"
      "@diez/targets": "*"
      "@diez/extractors": "*"
      "@diez/extractors-core": "*"
    peerDependencies:
      "typescript": "*"
  "@diez/compiler-core@*":
    dependencies:
      "@types/node": "*"
      "@diez/stdlib": "*"
  "@diez/targets@*":
    peerDependencies:
      "typescript": "*"
  "@diez/start@*":
    peerDependencies:
      "typescript": "*"
  "@diez/stdlib@*":
    peerDependencies:
      "typescript": "*"
  "@diez/extractors-core@*":
    peerDependencies:
      "typescript": "*"
  "@diez/extractors@*":
    peerDependencies:
      "typescript": "*"
  "@diez/generators@*":
    peerDependencies:
      "typescript": "*"
  "@diez/createproject@*":
    peerDependencies:
      "typescript": "*"
  "@diez/generation@*":
    peerDependencies:
      "typescript": "*"
```
